# Generated by Django 5.1.4 on 2026-06-02 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='activity_label_plural',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='game',
            name='activity_label_singular',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='game',
            name='category',
            field=models.CharField(choices=[('racing', 'Racing'), ('fps', 'FPS'), ('moba', 'MOBA'), ('fighting', 'Fighting'), ('general', 'General')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='game',
            name='level_group_label',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
