# Generated by Django 5.1.4 on 2026-06-02 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BigIntegerField(help_text='Time stored as milliseconds; other metric types use raw integer units.')),
                ('submitted_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_results', to='games.level')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_results', to='teams.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('user', 'team', 'level')},
            },
        ),
        migrations.CreateModel(
            name='TeamBenchmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_fast', models.BigIntegerField(blank=True, help_text='Par 1 / fast target (milliseconds for time games).', null=True)),
                ('target_slow', models.BigIntegerField(blank=True, help_text='Par 2 / slow target (milliseconds for time games).', null=True)),
                ('elite', models.BigIntegerField(blank=True, help_text='World record / elite benchmark (milliseconds for time games).', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_benchmarks', to='games.level')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benchmarks', to='teams.team')),
            ],
            options={
                'unique_together': {('team', 'level')},
            },
        ),
    ]
