# Generated by Django 5.1.4 on 2026-06-02 03:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_result_history(apps, schema_editor):
    MemberResult = apps.get_model('performances', 'MemberResult')
    MemberResultHistory = apps.get_model('performances', 'MemberResultHistory')
    for result in MemberResult.objects.all().iterator():
        MemberResultHistory.objects.create(
            user_id=result.user_id,
            team_id=result.team_id,
            level_id=result.level_id,
            value=result.value,
            entered_by_id=result.user_id,
            created_at=result.created_at,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_activity_label_plural_and_more'),
        ('performances', '0001_initial'),
        ('teams', '0003_teamjoinrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberResultHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BigIntegerField(help_text='Time stored as milliseconds; other metric types use raw integer units.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entered_member_result_history', to=settings.AUTH_USER_MODEL)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_result_history', to='games.level')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_result_history', to='teams.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_result_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(backfill_result_history, migrations.RunPython.noop),
    ]
