# Generated by Django 5.1.4 on 2026-06-02 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_teammigrationrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teammigrationrequest',
            name='source_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_reviewed_team_migration_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teammigrationrequest',
            name='status',
            field=models.CharField(choices=[('pending_source', 'Pending source org approval'), ('pending_target', 'Pending target org approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending_source', max_length=20),
        ),
    ]
